### ISSUE TITLE
Adjust voltage read percentage formula

### ISSUE THREAD

**Issue by joshua255** [SouthEugeneRoboticsTeam/ursa-driver-station#4]
I think you are currently using this code for getting a "percentage charged" value
`int batteryCharge(int voltage) => (voltage / 255 * 100).round();` 

At about 8v, a current percentage value of 62%, or a voltage value of about 157 out of 255, URSA stops working because of the low voltage, and that should be displayed as 0% remaining. (A computer battery at" 0%" still has quite a bit of voltage)

In URSA's code, line `133` of `ursa.ino` reads the voltage and scales it. You could change the scaling there so a 0 corresponds to right below the lowest functioning voltage if you would rather fix it in the robot code than here. Also, the voltage read in the robot still needs to be calibrated by adjusting `DACUnitsPerVolt`; I found a rough value but it wasn't ever checked carefully.

**Comment by andrewda** [comment]
Good idea! I'm also planning on averaging the battery voltage over the past 5 seconds or so because it's very jumpy right now.

**Comment by joshua255** [comment]
Can the icon fill by percent, and is voltage or percent shown next to the icon?

**Comment by andrewda** [comment]
Percentage is shown right now, and yeah I can try to get it to fill!

**Comment by joshua255** [comment]
Would voltage be more useful? That's how it is forthe FRC driverstation
